workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      groups:
        - ios-auth
      vars:
        BUNDLE_ID: "com.ageless.scanner"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Flutter clean
        script: flutter clean
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS app
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISS
        key_identifier: $APP_STORE_CONNECT_KE
        private_key: $APP_STORE_CONNECT_PRI
        submit_to_testflight: true
